### ISSUE TITLE
Session#automatically_recover does not propagage connection blocked/unblocked hooks

### ISSUE THREAD

**Issue by yaauie** [ruby-amqp/march_hare#141]
Motivation:

I am attempting to build back-pressure into the Logstash RabbitMQ Output plugin, so that we won't continue to publish on a connection when the connection has been flagged as blocked and will then resume publishing when that connection has been flagged as unblocked (see: https://github.com/logstash-plugins/logstash-output-rabbitmq/issues/85).

***

When subscribing to a connection's blocked/unblocked notifications with `Session#on_blocked` and `Session#unblocked`, that subscription is lost if a connection is broken and subsequently reestablished with `Session#automatically_recover`; application of the hooks are forwarded to the underlying `@connection`, so when `Session#automatically_recover` _replaces_ that ivar with a new connection object, previously-applied hooks are orphaned and no longer exist.

I suspect a similar solution to the shutdown hook propagation with [`Session#recover_shutdown_hooks`](https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L301) would suffice, but there may also be other edge-cases that prevent these hooks from being used reliably across connection recovery (e.g., is it possible to use supported hooks to define the transitions in a state machine describing the connection's blocked status? Is this still true when the underlying connection can be replaced?)

**Comment by michaelklishin** [comment]
Your understanding is correct, almost certainly it's a matter of updating new connection state just like we do for [shutdown hooks](https://github.com/ruby-amqp/march_hare/blob/master/lib/march_hare/session.rb#L301). March Hare historically has its own connection recovery implementation and there are no major reasons to switch to rely on the Java client to do it.

See Java client, it doesn't do anything sophisticated in order to [reinstall blocked/unblocked event handlers](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L590). Feel free to contribute a similar feature to March Hare :)

**Comment by yaauie** [comment]
@michaelklishin thanks for the quick response.

I see that the Java client also has [`RecoveryListener`](https://github.com/rabbitmq/rabbitmq-java-client/blob/b55bd20a1a236fc2d1ea9369b579770fa0237615/src/main/java/com/rabbitmq/client/RecoveryListener.java), and I believe similar would be necessary in March Hare in order to fully describe the possible transitions in a state machine of connection-blocked status. Do you see the rabbit-hole getting too deep in porting that behaviour too?

**Comment by michaelklishin** [comment]
Recovery listeners are not related to resource alarm notifications. Reinstalling them makes sense 👍

**Comment by yaauie** [comment]
This will be resolved with #142 once a release is rolled.

**Comment by michaelklishin** [comment]
There is one test left to fix but this is basically addressed in #141. Thanks @yaauie 👍👍
