### ISSUE TITLE
Unable to get multi-threading working

### ISSUE THREAD

**Issue by lardcanoe** [ruby-amqp/march_hare#76]
When I subscribe to a queue, and i have my channel prefetch 4, i would suspect 4 payloads to be worked on at the same time, but I am only seeing 1. I have played around with as many combos of thread_pool_size and :executor => ::MarchHare::ThreadPools as I can think of but nothing changes.

I created this gist https://gist.github.com/lardcanoe/afc43247401154e4b0c8 which is based off the non_blocking example.

I am upgrading from an ancient version of hot bunny where this works, so I know it is possible... :-)

```
➜  march_hare 1.7.12 git:(master) ✗ jruby --dev -J-Xmx1024m -J-Djruby.thread.pooling=true -J-verbose:gc -J-XX:+PrintGCTimeStamps ./example.rb
1.313: [GC 31232K->8704K(116224K), 0.0201110 secs]
hello world! 0
   working for 2.2684044843792455s
hello world! 1
   working for 2.8641889958616225s
hello world! 2
   working for 0.14870864668540962s
hello world! 3
   working for 1.894034775133878s
hello world! 4
   working for 0.7181932070184466s
hello world! 5
   working for 1.0377589474106612s
hello world! 6
   working for 1.713356347646346s
hello world! 7
   working for 2.596655787210624s
hello world! 8
   working for 1.9508658154661274s
hello world! 9
   working for 1.0137145610315375s
hello world! 10
   working for 2.0790365809675935s
```

When I look at Rabbit, i do see the 4 message unacked.

**Comment by michaelklishin** [comment]
March Hare passes the executor to the Java client. It then uses batched execution of server-sent methods (e.g. `basic.deliver`) in the executor. That currently means 1 thread per channel because we need to guarantee ordering.

So you can either use N channels or dispatch Ruby blocks to your own executor from the `subscribe` block.

Hot Bunnies used its own executor at some point, executing the `subscribe` block for every delivery in it. It did not guarantee any ordering.

**Comment by lardcanoe** [comment]
I tried N channels, example at https://gist.github.com/lardcanoe/afc43247401154e4b0c8#file-threads-rb, and that performs horribly. I played around with changing the number of threads, and the number of prefetches, and I haven't found anything that comes remotely close to the speed at which hot_bunny performed with all the other code being the same. I am sure there is some little thing I am overlooking... thanks!

**Comment by michaelklishin** [comment]
Your code uses prefetch = 1, manual acknowledgements and `Kernel#sleep`. The only thing you can control with this kind of setup is the number of threads available. Or dispatch to a thread pool to make sure your `subscribe` blocks return virtually immediately:

``` ruby
pool = MarchHare::ThreadPools.dynamically_growing

q.subscribe do |headers, msg|
  pool.submit do
    # actual work
    headers.ack
  end
end
```

This won't guarantee any order of processing (what Java client does per-channel).

I've taken a look and at least before the time Hot Bunnies was renamed 2 years ago, not a lot around consumer dispatch has changed.

As always, if something "performs horribly", use VisualVM or other profiler of choice. That means removing `sleep`s because they'd distort the results with sampling profilers.
